name: gaw_api
description: The API Package for the Get-a-Wash application stack
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.4.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  built_value: ^8.6.2
  built_value_generator: ^8.6.2
  built_collection: ^5.1.1
  dio: ^5.3.3
  mockito: ^5.4.2
  flutter_riverpod: ^2.3.10
  localstorage: ^4.0.0+1
  image_picker: ^1.0.4
  google_maps_flutter: ^2.5.0
  fl_chart: ^0.66.0
  flutter_polyline_points: ^2.0.0
  image: ^4.1.6
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6


