name: flutter_package_gaw_api
description: The API Package for the Get-a-Wash application stack
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.2.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  built_value: ^8.6.2
  built_value_generator: ^8.6.2
  built_collection: ^5.1.1
  dio: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6


